name: Continuous Integration
on: [push]
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install Nodejs Dependencies
        run: yarn
      - name: Unit Test
        run: yarn test
      - name: Deploy Test Coverage IF Branch main
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: coverage